#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
    root:password
  expire: False
users:
  - name: ${user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: ${groups}
    home: /home/${user}
    shell: /bin/bash
    lock_passwd: False
    ssh-authorized-keys:
      - ${ssh_public_key}
