#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true
users:
  - name: ${user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: ${groups}
    home: /home/${user}
    shell: /bin/bash
    lock_passwd: False
    ssh-authorized-keys:
      - ${ssh_public_key}
