#cloud-config
preserve_hostname: true
hostname: using-user-data
manage_etc_hosts: true
packages:
  - qemu-guest-agent
bootcmd:
  - [ip, route, add, default, via, "192.168.20.10"]
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, --now, --no-block, qemu-guest-agent]
  - [dnf, -y, upgrade]
user:
  name: ${user}
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: ${groups}
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ssh_public_key}
users:
  - default
  - name: root
    hashed_passwd: ${root_password}
    lock_passwd: false
power_state:
  mode: reboot
  message: Rebooting to apply changes
  timeout: 30
