#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true
packages:
  - qemu-guest-agent
write_files:
  - path: /etc/cloud/cloud.cfg.d/99_preserve_hostname.cfg
    owner: root:root
    permissions: "0644"
    content: "preserve_hostname: true"
bootcmd:
  - [ip, route, add, default, via, "192.168.20.10"]
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, --now, --no-block, qemu-guest-agent]
  - [dnf, -y, upgrade]
user:
  name: ${user}
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: ${groups}
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ssh_public_key}
users:
  - default
  - name: root
    hashed_passwd: ${root_password}
    lock_passwd: false
power_state:
  mode: reboot
  message: Rebooting to apply changes
  timeout: 30
