#cloud-config
preserve_hostname: true
hostname: ${hostname}
manage_etc_hosts: true
packages:
  - qemu-guest-agent
  - nftables
write_files:
  - path: /etc/sysctl.d/50-ipforward.conf
    content: net.ipv4.ip_forward=1
    owner: root:root
    permissions: "0o644"
    encoding: text/plain
    append: false
    defer: false
  - path: /etc/sysconfig/nftables.conf
    content: |
      table ip nat {
              chain postrouting {
                      type nat hook postrouting priority srcnat; policy accept;
                      oifname "eth1" masquerade
              }
      }
    owner: root:root
    permissions: "0o600"
    encoding: text/plain
    append: false
    defer: false
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, --now, --no-block, qemu-guest-agent]
  - [systemctl, enable, --now, --no-block, nftables]
  - [sysctl, --system]
  - [dnf, -y, upgrade]
user:
  name: ${user}
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: ${groups}
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ssh_public_key}
users:
  - default
  - name: root
    hashed_passwd: ${root_password}
    lock_passwd: false
power_state:
  mode: reboot
  message: Rebooting to apply changes
  timeout: 30
